# Generated by Django 5.1.6 on 2025-02-20 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the message.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time the message was created.')),
                ('is_from_user', models.BooleanField(help_text='True if the message is from the user, False if from the bot.')),
                ('user', models.ForeignKey(help_text='The user associated with this message.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='chat_messag_user_id_06b162_idx')],
            },
        ),
    ]
