# Generated by Django 5.1.6 on 2025-04-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_selectedactivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedactivity',
            unique_together={('user', 'activity')},
        ),
    ]
